FROM amd64/eclipse-temurin:21

WORKDIR /servisi

COPY ./ev_telemetry_servisi/NWTiS_REST_1.txt /servisi/NWTiS_REST_1.txt
COPY ./ev_telemetry_servisi/NWTiS_REST_2.txt /servisi/NWTiS_REST_2.txt
COPY ./ev_telemetry_servisi/NWTiS_REST_K.txt /servisi/NWTiS_REST_K.txt
COPY ./ev_telemetry_servisi/NWTiS_REST_R.txt /servisi/NWTiS_REST_R.txt
COPY ./ev_telemetry_servisi/NWTiS_REST_S.txt /servisi/NWTiS_REST_S.txt
COPY ./ev_telemetry_servisi/NWTiS_REST_V.txt /servisi/NWTiS_REST_V.txt

COPY ./ev_telemetry_servisi/target/ev_telemetry_servisi-1.0.0-jar-with-dependencies.jar /servisi/ev_telemetry_servisi-1.0.0-jar-with-dependencies.jar
COPY ./docker-entrypoint.servisi.sh /docker-entrypoint.sh

RUN chmod -R 777 /docker-entrypoint.sh

EXPOSE 8080
    
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["servisi"]