version: '3'
networks:
  nwtis:
    driver: bridge
    ipam:
      config:
        - subnet: 20.24.5.0/24
          gateway: 20.24.5.1

volumes:
  nwtis_h2_dz_2v:
    external: true
  nwtis_hsql_dz_2v:
    external: true
    
services:
  h2:
    image: nwtis_h2_dz_2i
    container_name: nwtis_h2_dz_2c
    build:
      context: .
      dockerfile: Dockerfile.h2
    volumes:
      -  type: volume
         source: nwtis_h2_dz_2v
         target: /opt/database
         volume:
            nocopy: true
    restart: unless-stopped
    networks:
      nwtis:
        ipv4_address: 20.24.5.4

  hsql:
    image: nwtis_hsql_dz_2i
    container_name: nwtis_hsql_dz_2c
    build:
      context: .
      dockerfile: Dockerfile.hsql
    volumes:
      -  type: volume
         source: nwtis_hsql_dz_2v
         target: /opt/data
         volume:
            nocopy: true
    restart: unless-stopped
    networks:
      nwtis:
        ipv4_address: 20.24.5.3
    depends_on:
      - h2
      
  app:
    image: nwtis_app_dz_2i
    container_name: nwtis_app_dz_2c  
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: unless-stopped
    networks:
      nwtis:
        ipv4_address: 20.24.5.2
    depends_on:
      - hsql
      
  servisi:
    image: nwtis_servisi_dz_2i
    container_name: nwtis_servisi_dz_2c
    build:
      context: .
      dockerfile: Dockerfile.servisi
    restart: unless-stopped
    ports:
      - 9080:8080
    networks:
      nwtis:
        ipv4_address: 20.24.5.5
    depends_on:
      - app